spring:
  application:
    name: chat-service
  #   config:
  # import: optional:configserver:http://localhost:8080
  cloud:
    config:
      enabled: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5435/chat_service_db
    username: minhduc8a2
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create

     
      

kafka-config:
  topic-name: chat-messages
  partitions: 3
  replicas: 1

server:
  port: 8084

jwt:
  secret: X0iDLiUGr5em1s0hWKnZCMdJ+irvhURKSo1faNKpGxY=
  expiration-time: 900000
  refresh-token:
    expiration-time: 604800000